<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Stores rubric text attached to a computed metric result.
 *
 * These rows are generated by the app during metric computation.
 */
class RubricResult extends Model
{
    public $primaryKey = 'rubric_results_id';
    public $timestamps = false;
    protected $fillable = [
        'tutoring_session_id', 'user_id', 'metric_result_id', 'status_level',
        'interpretation', 'algorithm_interpretation', 'recommended_action'
    ];
}